version: "3.4"

services:
  stratosd-tropos01-v1:
    container_name: stratos-tropos01-v1
    image: cyberguy85/stratos-delegation-tropos01:latest
    restart: always
    ports:
      - "26657:26657"
      - "26656:26656"
    volumes:
      - /root/.stchaind/:/root/.stchaind/
      - type: bind
        source: $PWD/config.ini
        target: /root/config.ini
        read_only: true
